"""Emulation script to demonstrate the anti-detection behavioral approach.

This script does NOT hit Facebook. Instead, it demonstrates how the various
layers (Network, Browser, Content, Timing) alter the requests and emulate
human behavior under the hood.
"""

import asyncio
import base64
import json
import logging
import os
import random
from pathlib import Path
from typing import Any

from fb_automation.anti_detection import AntiDetectionOrchestrator, AntiDetectionConfig
from fb_automation.models import IdentityContext
from fb_automation.image_mutator import ImageMutator, MutationConfig
from fb_automation.header_forge import AdvancedHeaderForge
from fb_automation.stochastic_timer import AdvancedStochasticTimer, TimingProfile

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

async def emulate_behavior() -> None:
    print("="*60)
    print(" 🕵️‍♂️ FACEBOOK AUTOMATION ANTI-DETECTION BEHAVIOR EMULATOR 🕵️‍♂️")
    print("="*60)
    print("This script demonstrates the mutations, delays, and headers")
    print("generated by our stealth systems to emulate a real human.")
    print("="*60 + "\n")

    # 1. Setup Identity
    identity = IdentityContext(
        account_id="demo_user_01",
        proxy_url="http://user:pass@proxy.residential.com:8080",
        user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        viewport={"width": 1920, "height": 1080},
        chrome_version="126.0.0.0",
        webgl_vendor="Google Inc. (NVIDIA)",
        webgl_renderer="ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)"
    )

    print("👤 [IDENTITY LAYER] Created Identity Context:")
    print(f"   - User Agent: {identity.user_agent}")
    print(f"   - WebGL: {identity.webgl_renderer}")
    print(f"   - Viewport: {identity.viewport}")
    print()

    # 2. Timing Layer (Stochastic Timer)
    print("⏳ [TIMING LAYER] Emulating Human Delay Distributions:")
    timer = AdvancedStochasticTimer()
    
    # Emulate typing a caption
    caption = "Check out this awesome new update!"
    typing_delay = timer.type_text_time(caption, profile=TimingProfile.CAUTIOUS)
    print(f"   - Emulated typing '{caption}' (Cautious profile): {typing_delay:.2f} seconds")
    
    # Emulate think time
    think_delay = timer.think_time(min_ms=500, max_ms=2500)
    print(f"   - Emulated 'think/read' time: {think_delay:.2f} seconds")
    print()

    # 3. Network Layer (Header Forge)
    print("🌐 [NETWORK LAYER] Forging Strict Chrome Headers:")
    tokens = {
        "fb_dtsg": "NAcOa_1234567890:1234567890",
        "lsd": "AVq1w2e3r4t5y6",
        "user_id": "1000123456789"
    }
    graphql_headers = AdvancedHeaderForge.forge_graphql_headers(tokens, identity)
    
    print("   Generated Request Headers (Notice ordering and sec-ch-ua exactness):")
    for k, v in graphql_headers.items():
        if k in ('user-agent', 'sec-ch-ua', 'sec-ch-ua-platform'):
            print(f"   > {k}: {v}")
    print()

    # 4. Content Layer (Image Mutation)
    print("🖼️ [CONTENT LAYER] Emulating Perceptual Hash Mutation (rupload.py):")
    mutator = ImageMutator(MutationConfig(
        noise_intensity=0.03,  # Slight noise
        quality_range=(85, 92),
        dimension_jitter_pct=0.01,
        strip_exif=True
    ))

    # Create a dummy image for demonstration
    try:
        from PIL import Image
        dummy_path = "dummy_demo_image.jpg"
        img = Image.new('RGB', (800, 600), color=(73, 109, 137))
        img.save(dummy_path)
        
        with open(dummy_path, "rb") as f:
            original_bytes = f.read()
            
        print(f"   - Original image size: {len(original_bytes)} bytes")
        
        mutated_bytes, info = await mutator.mutate_image(original_bytes)
        
        print(f"   - Mutated image size: {len(mutated_bytes)} bytes")
        print(f"   - Mutation operations applied: {info.get('operations', [])}")
        print(f"   - New Dimensions: {info.get('new_dimensions')}")
        print(f"   - Quality Used: {info.get('quality')}")
        
        # Cleanup
        os.remove(dummy_path)
    except ImportError:
        print("   - PIL not installed, skipping image mutation demo.")
    except Exception as e:
        print(f"   - Error during mutation demo: {e}")
    print()
    
    print("🛡️ [ORCHESTRATION LAYER] Summary:")
    print("By combining exact header mimicking, JA3/JA4 TLS spoofing (via tls-client),")
    print("stochastic non-linear timing, and payload mutation, the system eliminates")
    print("deterministic signatures that heuristic detection engines look for.")
    print("="*60)


if __name__ == "__main__":
    asyncio.run(emulate_behavior())
